# Use an official Ubuntu runtime as a parent image
FROM gcc:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY /Stock/ /app/Stock
# COPY . /app/Bank    
COPY /Data/ /app/Data

COPY /Bank/ /app/Bank


# Compile the C++ program
RUN g++ -std=c++11 /app/Bank/bank.cpp -o /app/Bank/bank

# Set the command to run when the container starts
CMD ["./Bank/bank"]