# Use an official Ubuntu runtime as a parent image
FROM gcc:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY StockMarket /app/StockMarket
COPY /Stock/ /app/Stock

# Compile the C++ program
RUN g++ -std=c++11 /app/StockMarket/stockMarket.cpp -o /app/StockMarket/StockMarket

# Set the command to run when the container starts
CMD [".app/StockMarket/StockMarket"]